// <auto-generated />
namespace Demo.Migration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeCreateTimeColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeCreateTimeColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201807110517104_changeCreateTimeColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
